### ISSUE TITLE
Detecting multiple subtypes of stx2?

### ISSUE THREAD

**Issue by haejh88** [LanLab/STECFinder#1]
Hi, 
We have a strain that was run through Bionumerics, and it detected both stx2a and stx2c. I tried STECFinder on the same strain, and it gave me stx2c when I used raw sequences. I tried different thresholds but STECFinder still only identifies stx2c. 
Can STECFinder identify multiple stx2 subtypes, especially stx2a/stx2c?

Thank you,

**Comment by mjohnpayne** [comment]
Hi, 
I will have a look at this and get back to you soon!

**Comment by mjohnpayne** [comment]
Hi,
At the moment STECfinder will only report the best matches for stx1 and stx2 not multiple matches. STECfinder was originally designed to itdentify STEC strains, not really to subtype stx. However we are investigating the best approach to allow complete stx subtyping as you suggest as an additional utility. Thanks for your interest! I will update this issue with any updates soon!

**Comment by mjohnpayne** [comment]
Hello @haejh88. 
Sorry for the delay. Version 1.1 of STECfinder can now call multiple stx2 alleles (only from raw reads). I will update the conda package as well so if you update it there then it should give you calls as you expect. If you run into any issues let me know!

**Comment by haejh88** [comment]
That's great, thank you so much for the update!
