### ISSUE TITLE
Feature Request: Handle Paired and Single Reads Together

### ISSUE THREAD

**Issue by schorlton** [LanLab/STECFinder#3]
Hi,

Thanks for the great tool! Is it possible to handle both paired-end and single-end reads in the same analysis? Often preprocessing tools or pipelines will merge paired-ends such that there is both paired- and single-end reads for the same sample.

Thanks!

**Comment by mjohnpayne** [comment]
Hi,

Glad you find it helpful!

Would having STECFinder accept a tab delimited file containing strain IDs and read paths work? i.e this per isolate.

`StrainID     forward read path     reverse read path     single-end read`

**Comment by schorlton** [comment]
Yes that's a good idea. I'm pretty indifferent to how the data is specified and more care that it's a bit more flexible than now, which this approach would accomplish. Feel free to add/edit that to my pull request if you think the tab delimited file is better. I may be able to contribute this over coming weeks...just need to figure out how and find time.
